# Base configs
baseurl: "https://photography.deniskerner.de"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-V03H9W7H5G"

# UI configs
title: "Photography by Denis Kerner"
subtitle: "See the world through my eyes!"
author: "Denis Kerner"
header:
 title: "Photography"
 subtitle: "by Denis Kerner"
footer:
 name: "Hey there, my name is Denis"
 bio: "I am a photographer and circus acrobat from Germany. I love creating visual impressions of different circus arts."
 # github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
# web_design: "AJ"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  # twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/deniskerner_photography"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
